=== TNTworks/flogo-web/libs/lib-server/core/src/lib/schemas/v1.0.0/app.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://github.com/project-flogo/flogo-web/schemas/1.0.0/app.json",
  "type": "object",
  "required": ["name", "type", "appModel"],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "title": "The name of the app"
    },
    "type": {
      "type": "string",
      "title": "The type of the application",
      "default": "flogo:app",
      "const": "flogo:app"
    },
    "version": {
      "type": "string",
      "title": "Version of this app"
    },
    "appModel": {
      "type": "string",
      "title": "Flogo app model version"
    },
    "description": {
      "type": "string",
      "title": "The description of this app",
      "default": ""
    },
    "properties": {
      "type": "array",
      "items": {
        "ref": "common.json#/definitions/appProperty"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "triggers": {
      "type": "array",
      "items": {
        "$ref": "trigger.json"
      }
    },
    "actions": {
      "type": "array",
      "items": {
        "$ref": "action.json"
      }
    },
    "resources": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/resource"
      }
    }
  },
  "definitions": {
    "resource": {
      "type": "object",
      "required": ["id", "data"],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^\\w+:\\w+$"
        },
        "data": {
          "type": "object"
        }
      }
    }
  }
}

=== TNTworks/flogo-web/apps/server/src/modules/transfer/tests/samples/standard-app.json
{
  "name": "RestApp",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "My rest app",
  "appModel": "1.0.0",
  "triggers": [
    {
      "id": "receive_http_message",
      "ref": "some_path_to_repo/trigger/rest",
      "name": "Receive HTTP Message",
      "description": "Simple REST Trigger",
      "settings": {
        "port": "9094"
      },
      "handlers": [
        {
          "settings": {
            "method": "GET",
            "path": "/status/:id",
            "autoIdReply": null,
            "useReplyHandler": "true"
          },
          "action": {
            "ref": "github.com/project-flogo/flow",
            "data": {
              "flowURI": "res://flow:get_status"
            },
            "mappings": {
              "input": [
                {
                  "mapTo": "id",
                  "type": "assign",
                  "value": "params.id"
                }
              ],
              "output": [
                {
                  "mapTo": "code",
                  "type": "assign",
                  "value": "$.code"
                },
                {
                  "mapTo": "data",
                  "type": "assign",
                  "value": "status"
                }
              ]
            }
          }
        }
      ]
    }
  ],
  "resources": [
    {
      "id": "flow:get_status",
      "data": {
        "name": "GetStatus",
        "description": "",
        "metadata": {
          "input": [
            {
              "name": "id",
              "type": "string"
            }
          ],
          "output": [
            {
              "name": "status",
              "type": "object"
            },
            {
              "name": "code",
              "type": "integer"
            }
          ]
        },
        "tasks": [
          {
            "id": "log_2",
            "activity": {
              "name": "Log Message",
              "description": "Simple Log Activity",
              "ref": "some_path_to_repo/activity/log",
              "input": {
              },
              "mappings": {
                "input": [
                  {
                    "type": "assign",
                    "value": "$flow.id",
                    "mapTo": "message"
                  }
                ]
              }
            }
          }
        ],
        "links": [
        ],
        "errorHandler": {
          "tasks": [
            {
              "id": "log_6",
              "activity": {
                "ref": "some_path_to_repo/activity/log",
                "input": {
                  "message": "log in error handler"
                },
                "output": {
                },
                "mappings": {
                }
              }
            }
          ]
        }
      }
    }
  ]
}

=== TNTworks/flogo-web/apps/server/src/config/sample-app.json
{
  "name": "Sample app",
  "type": "flogo:app",
  "version": "0.0.1",
  "appModel": "1.0.0",
  "description": "Sample flogo app",
  "triggers": [
    {
      "id": "receiver",
      "ref": "github.com/TNTworks/flogo-contrib/trigger/rest",
      "name": "Receiver",
      "description": "Simple REST Trigger",
      "settings": {
        "port": "9998"
      },
      "handlers": [
        {
          "action": {
            "ref": "github.com/project-flogo/flow",
            "data": {
              "flowURI": "res://flow:aws_iot_sample"
            },
            "mappings": {
              "output": [
                {
                  "mapTo": "code",
                  "type": "assign",
                  "value": "$.code"
                },
                {
                  "mapTo": "data",
                  "type": "assign",
                  "value": "$.message"
                }
              ]
            }
          },
          "settings": {
            "method": "GET",
            "path": "/awsiot/status",
            "autoIdReply": "true",
            "useReplyHandler": "true"
          }
        }
      ]
    },
    {
      "id": "timer_trigger",
      "ref": "github.com/TNTworks/flogo-contrib/trigger/timer",
      "name": "Timer Trigger",
      "description": "Simple Timer trigger",
      "settings": {},
      "handlers": [
        {
          "action": {
            "ref": "github.com/project-flogo/flow",
            "data": {
              "flowURI": "res://flow:hello_world"
            }
          },
          "settings": {
            "repeating": "true",
            "startDate": "",
            "hours": "",
            "minutes": "",
            "seconds": "15"
          }
        }
      ]
    }
  ],
  "resources": [
    {
      "id": "flow:hello_world",
      "data": {
        "name": "HelloWorld",
        "tasks": [
          {
            "id": "counter_1",
            "name": "Number Counter",
            "description": "Simple Global Counter Activity",
            "activity": {
              "ref": "github.com/TNTworks/flogo-contrib/activity/counter",
              "settings": {
                "counterName": "myCounter"
              }
            }
          },
          {
            "id": "log_1",
            "name": "Logger",
            "description": "Simple Log Activity",
            "activity": {
              "ref": "github.com/TNTworks/flogo-contrib/activity/log",
              "input": {
                "message": "hello world",
                "flowInfo": "true",
                "addToFlow": "true"
              }
            }
          }
        ],
        "links": [
          {
            "from": "counter_1",
            "to": "log_1"
          }
        ]
      }
    }
  ]
}
